//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbusmeasure
    {
        public string ID { get; set; }
        public Nullable<int> UAYCID { get; set; }
        public Nullable<int> UBYCID { get; set; }
        public Nullable<int> UCYCID { get; set; }
        public Nullable<int> UABYCID { get; set; }
        public Nullable<int> UACYCID { get; set; }
        public Nullable<int> UBCYCID { get; set; }
    }
}
