//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcommand
    {
        public int ID { get; set; }
        public Nullable<int> SCHEMEID { get; set; }
        public Nullable<int> SCHEMEINDEX { get; set; }
        public string CMDELEMENTID { get; set; }
        public Nullable<int> CMDELEMENTSTYLE { get; set; }
        public Nullable<System.DateTime> CMDDATETIME { get; set; }
        public Nullable<int> CZH { get; set; }
        public Nullable<int> YKYTH { get; set; }
        public Nullable<double> YKYTVALUE { get; set; }
        public Nullable<int> CONTROLMODEL { get; set; }
        public Nullable<int> CHANNEL { get; set; }
        public Nullable<int> DEALTAG { get; set; }
        public Nullable<System.DateTime> DEALDATETIME { get; set; }
        public Nullable<int> CONTROLAREA { get; set; }
        public Nullable<int> CMDACTION { get; set; }
        public Nullable<float> YTVALUE { get; set; }
        public Nullable<int> YKYTTYPE { get; set; }
    }
}
