//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblconductortype
    {
        public string ID { get; set; }
        public string TYPENAME { get; set; }
        public Nullable<int> STYLE { get; set; }
        public string VOLTAGELEVELID { get; set; }
        public Nullable<double> R_RATE { get; set; }
        public Nullable<double> X_RATE { get; set; }
        public Nullable<double> G_RATE { get; set; }
        public Nullable<double> B_RATE { get; set; }
        public Nullable<double> RADIUS { get; set; }
        public Nullable<double> SECTIONAREA { get; set; }
        public Nullable<double> ECONOMICCURRENT { get; set; }
        public Nullable<double> SECURECURRENT { get; set; }
        public Nullable<double> MAXIMALCURRENT { get; set; }
        public Nullable<int> CONDUCTORCOUNT { get; set; }
        public Nullable<double> BUNDLEDCONDUCTORSPACE { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<double> BREAKINGFORCE { get; set; }
        public Nullable<double> ELASTICITYCOEFFICIENT { get; set; }
        public Nullable<double> EXPANSIONCOEFFICIENT { get; set; }
        public Nullable<double> UNITPRICE { get; set; }
        public Nullable<int> LOCALCHOICE { get; set; }
        public Nullable<int> SELECTCOUNT { get; set; }
    }
}
