//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldepartment
    {
        public string ID { get; set; }
        public string PARTNAME { get; set; }
        public string FULLNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string OFFICEADDRESS { get; set; }
        public string OFFICEPOSTCODE { get; set; }
        public string OFFICEFAX { get; set; }
    }
}
