//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblelementstate
    {
        public int ID { get; set; }
        public string ELEMENTID { get; set; }
        public Nullable<long> ELEMENTSTYLE { get; set; }
        public string CONTROLSTATE { get; set; }
        public string SIGNTAGSTATE { get; set; }
        public string HANDUNLOCKPROTECTIONSTATE { get; set; }
        public string AUTOUNLOCKPROTECTIONSTATE { get; set; }
        public string EXCEPTIONSTATE { get; set; }
        public string ACTIONOUTSTATE { get; set; }
        public string BELOCKSTATE { get; set; }
        public Nullable<System.DateTime> LOCKSTARTTIME { get; set; }
        public Nullable<int> ADVICELOCKSEC { get; set; }
        public Nullable<int> PREPARLOCKSEC { get; set; }
        public Nullable<int> SUCCESSLOCKSEC { get; set; }
        public Nullable<int> FAILURELOCKSEC { get; set; }
        public Nullable<int> SLIPTAPLOCKSEC { get; set; }
        public Nullable<int> REPEATEDFAILURELOCKSEC { get; set; }
        public Nullable<int> REPEATEDFAILURECOUNT { get; set; }
        public Nullable<int> MAXREPEATEDFAILURECOUNT { get; set; }
    }
}
