//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedpowerqualitymeasure
    {
        public string ID { get; set; }
        public Nullable<int> FREQUENCYYCID { get; set; }
        public Nullable<int> UAFLICKERYCID { get; set; }
        public Nullable<int> UBFLICKERYCID { get; set; }
        public Nullable<int> UCFLICKERYCID { get; set; }
        public Nullable<int> VOLUNBALANCEYCID { get; set; }
        public Nullable<int> CURRENTUNBALANCEYCID { get; set; }
        public Nullable<int> UATHDYCID { get; set; }
        public Nullable<int> UBTHDYCID { get; set; }
        public Nullable<int> UCTHDYCID { get; set; }
        public Nullable<int> UAHARMONIC3YCID { get; set; }
        public Nullable<int> UBHARMONIC3YCID { get; set; }
        public Nullable<int> UCHARMONIC3YCID { get; set; }
        public Nullable<int> UAHARMONIC5YCID { get; set; }
        public Nullable<int> UBHARMONIC5YCID { get; set; }
        public Nullable<int> UCHARMONIC5YCID { get; set; }
        public Nullable<int> UAHARMONIC7YCID { get; set; }
        public Nullable<int> UBHARMONIC7YCID { get; set; }
        public Nullable<int> UCHARMONIC7YCID { get; set; }
        public Nullable<int> UAHARMONIC9YCID { get; set; }
        public Nullable<int> UBHARMONIC9YCID { get; set; }
        public Nullable<int> UCHARMONIC9YCID { get; set; }
        public Nullable<int> UAHARMONIC11YCID { get; set; }
        public Nullable<int> UBHARMONIC11YCID { get; set; }
        public Nullable<int> UCHARMONIC11YCID { get; set; }
        public Nullable<int> IATHDYCID { get; set; }
        public Nullable<int> IBTHDYCID { get; set; }
        public Nullable<int> ICTHDYCID { get; set; }
        public Nullable<int> IAHARMONIC3YCID { get; set; }
        public Nullable<int> IBHARMONIC3YCID { get; set; }
        public Nullable<int> ICHARMONIC3YCID { get; set; }
        public Nullable<int> IAHARMONIC5YCID { get; set; }
        public Nullable<int> IBHARMONIC5YCID { get; set; }
        public Nullable<int> ICHARMONIC5YCID { get; set; }
        public Nullable<int> IAHARMONIC7YCID { get; set; }
        public Nullable<int> IBHARMONIC7YCID { get; set; }
        public Nullable<int> ICHARMONIC7YCID { get; set; }
        public Nullable<int> IAHARMONIC9YCID { get; set; }
        public Nullable<int> IBHARMONIC9YCID { get; set; }
        public Nullable<int> ICHARMONIC9YCID { get; set; }
        public Nullable<int> IAHARMONIC11YCID { get; set; }
        public Nullable<int> IBHARMONIC11YCID { get; set; }
        public Nullable<int> ICHARMONIC11YCID { get; set; }
    }
}
