//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedtsfmeasure
    {
        public string ID { get; set; }
        public Nullable<int> POWERFACTORAYCID { get; set; }
        public Nullable<int> POWERFACTORBYCID { get; set; }
        public Nullable<int> POWERFACTORCYCID { get; set; }
        public Nullable<int> UAYCID { get; set; }
        public Nullable<int> UBYCID { get; set; }
        public Nullable<int> UCYCID { get; set; }
        public Nullable<int> IAYCID { get; set; }
        public Nullable<int> IBYCID { get; set; }
        public Nullable<int> ICYCID { get; set; }
        public Nullable<int> PAYCID { get; set; }
        public Nullable<int> PBYCID { get; set; }
        public Nullable<int> PCYCID { get; set; }
        public Nullable<int> QAYCID { get; set; }
        public Nullable<int> QBYCID { get; set; }
        public Nullable<int> QCYCID { get; set; }
        public Nullable<int> THDUAYCID { get; set; }
        public Nullable<int> THDUBYCID { get; set; }
        public Nullable<int> THDUCYCID { get; set; }
        public Nullable<int> THDIAYCID { get; set; }
        public Nullable<int> THDIBYCID { get; set; }
        public Nullable<int> THDICYCID { get; set; }
        public Nullable<int> HDUAYCID3 { get; set; }
        public Nullable<int> HDUBYCID3 { get; set; }
        public Nullable<int> HDUCYCID3 { get; set; }
        public Nullable<int> HDUAYCID5 { get; set; }
        public Nullable<int> HDUBYCID5 { get; set; }
        public Nullable<int> HDUCYCID5 { get; set; }
        public Nullable<int> HDUAYCID7 { get; set; }
        public Nullable<int> HDUBYCID7 { get; set; }
        public Nullable<int> HDUCYCID7 { get; set; }
        public Nullable<int> HDUAYCID9 { get; set; }
        public Nullable<int> HDUBYCID9 { get; set; }
        public Nullable<int> HDUCYCID9 { get; set; }
        public Nullable<int> HDIAYCID3 { get; set; }
        public Nullable<int> HDIBYCID3 { get; set; }
        public Nullable<int> HDICYCID3 { get; set; }
        public Nullable<int> HDIAYCID5 { get; set; }
        public Nullable<int> HDIBYCID5 { get; set; }
        public Nullable<int> HDICYCID5 { get; set; }
        public Nullable<int> HDIAYCID7 { get; set; }
        public Nullable<int> HDIBYCID7 { get; set; }
        public Nullable<int> HDICYCID7 { get; set; }
        public Nullable<int> HDIAYCID9 { get; set; }
        public Nullable<int> HDIBYCID9 { get; set; }
        public Nullable<int> HDICYCID9 { get; set; }
        public Nullable<int> FREQUENCYYCIDA { get; set; }
        public Nullable<int> FREQUENCYBYCID { get; set; }
        public Nullable<int> FREQUENCYCYCID { get; set; }
        public Nullable<int> CAPACITANCE_1YXID { get; set; }
        public Nullable<int> CAPACITANCE_2YXID { get; set; }
        public Nullable<int> CAPACITANCE_3YXID { get; set; }
        public Nullable<int> CAPACITANCE_4YXID { get; set; }
        public Nullable<int> CAPACITANCE_5YXID { get; set; }
        public Nullable<int> CAPACITANCE_6YXID { get; set; }
        public Nullable<int> CAPACITANCE_7YXID { get; set; }
        public Nullable<int> CAPACITANCE_8YXID { get; set; }
        public Nullable<int> CAPACITANCE_9YXID { get; set; }
        public Nullable<int> CAPACITANCE_10YXID { get; set; }
        public Nullable<int> CAPACITANCE_11YXID { get; set; }
        public Nullable<int> CAPACITANCE_12YXID { get; set; }
        public Nullable<int> CAPACITANCE_13YXID { get; set; }
        public Nullable<int> CAPACITANCE_14YXID { get; set; }
        public Nullable<int> CAPACITANCE_15YXID { get; set; }
        public Nullable<int> CAPACITANCE_16YXID { get; set; }
        public Nullable<int> CAPACITANCE_17YXID { get; set; }
        public Nullable<int> CAPACITANCE_18YXID { get; set; }
        public Nullable<int> CAPACITANCE_19YXID { get; set; }
        public Nullable<int> CAPACITANCE_20YXID { get; set; }
        public Nullable<int> CAPACITANCE_21YXID { get; set; }
        public Nullable<int> BUSCTYKID { get; set; }
        public Nullable<int> INPUTDELAYYKID { get; set; }
        public Nullable<int> EXCISIONDELAYYKID { get; set; }
        public Nullable<int> NEXTINPUTDELAYYKID { get; set; }
        public Nullable<int> TARGETPFYKID { get; set; }
        public Nullable<int> EXCISIONMODEYKID { get; set; }
        public Nullable<int> INPUTTHRESHOLDYKID { get; set; }
        public Nullable<int> EXCISIONTHRESHOLDYKID { get; set; }
        public Nullable<int> VOLTAGEUPPERTHRESHOLDYKID { get; set; }
        public Nullable<int> VOLTAGELOWERTHRESHOLDYKID { get; set; }
        public Nullable<int> THDUUPPERTHRESHOLDYKID { get; set; }
        public Nullable<int> THDIUPPERTHRESHOLDYKID { get; set; }
        public Nullable<int> BAUDYKID { get; set; }
        public Nullable<int> ADDRIDYKID { get; set; }
        public Nullable<int> CODEYKID { get; set; }
        public Nullable<int> PHASEYKID { get; set; }
        public Nullable<int> TOTALPHASEYKID { get; set; }
        public Nullable<int> C1_QYKID { get; set; }
        public Nullable<int> C2_QYKID { get; set; }
        public Nullable<int> C3_QYKID { get; set; }
        public Nullable<int> C4_QYKID { get; set; }
        public Nullable<int> C5_QYKID { get; set; }
        public Nullable<int> C6_QYKID { get; set; }
        public Nullable<int> C7_QYKID { get; set; }
        public Nullable<int> C8_QYKID { get; set; }
        public Nullable<int> C9_QYKID { get; set; }
        public Nullable<int> C10_QYKID { get; set; }
        public Nullable<int> C11_QYKID { get; set; }
        public Nullable<int> C12_QYKID { get; set; }
        public Nullable<int> C13_QYKID { get; set; }
        public Nullable<int> C14_QYKID { get; set; }
        public Nullable<int> C15_QYKID { get; set; }
        public Nullable<int> C16_QYKID { get; set; }
        public Nullable<int> C17_QYKID { get; set; }
        public Nullable<int> C18_QYKID { get; set; }
        public Nullable<int> C19_QYKID { get; set; }
        public Nullable<int> C20_QYKID { get; set; }
        public Nullable<int> C21_QYKID { get; set; }
        public Nullable<int> AUTOCONTROLYKID { get; set; }
        public Nullable<int> MANUALCONTROLYKID { get; set; }
        public Nullable<int> CAPACITANCECONTROL1_16YKID { get; set; }
        public Nullable<int> CAPACITANCECONTROL17_21YKID { get; set; }
    }
}
