//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedtrans
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string FEEDID { get; set; }
        public string VOLTAGELEVELID { get; set; }
        public string TRANSFORMERTYPEID { get; set; }
        public string SERVEMODE { get; set; }
        public bool ISONLOADTAPCHANGER { get; set; }
        public Nullable<double> R { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> G { get; set; }
        public Nullable<double> B { get; set; }
        public string TAPCHANGERID { get; set; }
        public string LOADLEVEL { get; set; }
        public string CHARGEMODE { get; set; }
        public Nullable<bool> ISONEPHASETRANS { get; set; }
        public Nullable<bool> ISMODULATINGCAPACITYTRANS { get; set; }
        public Nullable<bool> ISTHREEPHASEUNBALANCED { get; set; }
        public Nullable<bool> ISOLTC { get; set; }
        public string TRADECODE { get; set; }
        public string ELECTYPECODE { get; set; }
        public Nullable<double> EXPECTLIFETIME { get; set; }
        public Nullable<System.DateTime> STARTUSINGTIME { get; set; }
        public string GRAPHID { get; set; }
        public string DESCRIPTION { get; set; }
        public string ALIASNAME { get; set; }
    
        public virtual tblfeeder tblfeeder { get; set; }
        public virtual tblfeedtransmeasure tblfeedtransmeasure { get; set; }
    }
}
