//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedcapacitormeasure
    {
        public string id { get; set; }
        public Nullable<int> UYCID { get; set; }
        public Nullable<int> IYCID { get; set; }
        public Nullable<int> QYCID { get; set; }
        public Nullable<int> PFYCID { get; set; }
        public Nullable<int> QCYCID { get; set; }
        public Nullable<int> TARGETPFYCID { get; set; }
        public Nullable<int> ACTIONCOUNTTOTALYCID { get; set; }
        public Nullable<int> SWITCHYXID { get; set; }
        public Nullable<int> WORKMODEYCID { get; set; }
        public Nullable<int> GUARDSIGNALYXID { get; set; }
        public Nullable<int> CONSERVATIONYCID { get; set; }
    }
}
