//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedcapacitorcontrol
    {
        public string ID { get; set; }
        public int VOLCTRLMODYCVAL { get; set; }
        public int QCTRLMODYTVAL { get; set; }
        public int COSCTRLMODYCVAL { get; set; }
        public int VOLCTRLMODYTVAL { get; set; }
        public int COSCTRLMODYTVAL { get; set; }
        public int QCTRLMODYCVAL { get; set; }
        public Nullable<int> PUTONYXVAL { get; set; }
        public Nullable<int> PUTOFFYXVAL { get; set; }
        public Nullable<int> DISTANTYXVAL { get; set; }
        public Nullable<int> LOCALYXVAL { get; set; }
        public Nullable<int> PUTONYKVAL { get; set; }
        public Nullable<int> PUTOFFYKVAL { get; set; }
        public Nullable<int> DISTANTYKVAL { get; set; }
        public Nullable<int> LOCALYKVAL { get; set; }
    }
}
