//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblformulasources
    {
        public int RowID { get; set; }
        public string FormulaParentID { get; set; }
        public string FormulabNameID { get; set; }
        public string FormulaID { get; set; }
        public string SourceID { get; set; }
        public string SourceState { get; set; }
    }
}
