//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedsstsmeasure
    {
        public string ID { get; set; }
        public Nullable<int> U1AYCID { get; set; }
        public Nullable<int> U1BYCID { get; set; }
        public Nullable<int> U1CYCID { get; set; }
        public Nullable<int> I1AYCID { get; set; }
        public Nullable<int> I1BYCID { get; set; }
        public Nullable<int> I1CYCID { get; set; }
        public Nullable<int> U2AYCID { get; set; }
        public Nullable<int> U2BYCID { get; set; }
        public Nullable<int> U2CYCID { get; set; }
        public Nullable<int> I2AYCID { get; set; }
        public Nullable<int> I2BYCID { get; set; }
        public Nullable<int> I2CYCID { get; set; }
        public Nullable<int> I3AYCID { get; set; }
        public Nullable<int> I3BYCID { get; set; }
        public Nullable<int> I3CYCID { get; set; }
        public Nullable<int> SWITCH1YXID { get; set; }
        public Nullable<int> SWITCH2YXID { get; set; }
    }
}
