//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgraphtopoterminal
    {
        public int ROWID { get; set; }
        public string NAME { get; set; }
        public string CAPTION { get; set; }
        public string ID { get; set; }
        public Nullable<int> TAG { get; set; }
        public string VOL { get; set; }
        public Nullable<int> STID { get; set; }
        public Nullable<int> LINKCOUNT { get; set; }
        public string LINKS { get; set; }
        public Nullable<int> EQUIPCOUNT { get; set; }
        public string GRAPHID { get; set; }
        public string FEEDID { get; set; }
        public string LINK { get; set; }
        public string LINKFOOT { get; set; }
        public Nullable<int> PARENTID { get; set; }
    }
}
