//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblloginuser
    {
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERIP { get; set; }
        public string USERMAC { get; set; }
        public string USERHOSTNAME { get; set; }
        public Nullable<System.DateTime> LOGINTIME { get; set; }
        public Nullable<System.DateTime> INVALIDTIME { get; set; }
    }
}
