//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblprogrammgr
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string command { get; set; }
        public Nullable<int> dependency_id { get; set; }
        public int start_number { get; set; }
        public int start_interval { get; set; }
        public Nullable<int> kill_count { get; set; }
        public Nullable<System.DateTime> kill_time { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> sign_time { get; set; }
        public string status { get; set; }
        public string result { get; set; }
    }
}
