//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblprogrammgr
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMMAND { get; set; }
        public Nullable<int> DEPENDENCY_ID { get; set; }
        public Nullable<int> START_NUMBER { get; set; }
        public Nullable<int> START_INTERVAL { get; set; }
        public Nullable<int> KILL_COUNT { get; set; }
        public Nullable<System.DateTime> KILL_TIME { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> SIGN_TIME { get; set; }
        public string STATUS { get; set; }
        public string RESULT { get; set; }
    }
}
