//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsubstation
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string VOLTAGELEVELID { get; set; }
        public string SUBCONTROLAREAID { get; set; }
        public string CZH { get; set; }
        public Nullable<bool> ISROOTSTATION { get; set; }
        public Nullable<bool> ISCOMBINEMONITORED { get; set; }
        public string SPECIALITY { get; set; }
        public string STATIONKIND { get; set; }
        public string ALIASNAME { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
