//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltransformermeasure
    {
        public string ID { get; set; }
        public Nullable<int> HPYCID { get; set; }
        public Nullable<int> HQYCID { get; set; }
        public Nullable<int> HIYCID { get; set; }
        public Nullable<int> MPYCID { get; set; }
        public Nullable<int> MQYCID { get; set; }
        public Nullable<int> MIYCID { get; set; }
        public Nullable<int> LPYCID { get; set; }
        public Nullable<int> LQYCID { get; set; }
        public Nullable<int> LIYCID { get; set; }
        public Nullable<int> HTAPCHANGERYCID { get; set; }
        public Nullable<int> MTAPCHANGERYCID { get; set; }
    }
}
