//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public string ID { get; set; }
        public string USERNAME { get; set; }
        public string REALNAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string POSTCODE { get; set; }
        public string DEPARTID { get; set; }
        public string NATIVEIP2 { get; set; }
        public string LOGINSTATUS { get; set; }
        public Nullable<System.DateTime> LOGINTIME { get; set; }
        public Nullable<System.DateTime> EXITTIME { get; set; }
        public string NATIVEIP1 { get; set; }
        public Nullable<System.DateTime> NOWTIME { get; set; }
        public string EMPLOYEEID { get; set; }
        public string POSITION { get; set; }
    }
}
