//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblytparam
    {
        public string YTCODE { get; set; }
        public string YTKIND { get; set; }
        public Nullable<int> CONTROLAREA { get; set; }
        public int ID { get; set; }
        public string NAME { get; set; }
        public string STATIONID { get; set; }
        public string CMDELEMENTID { get; set; }
        public Nullable<int> CMDELEMENTSTYLE { get; set; }
        public string CZH { get; set; }
        public string YTH { get; set; }
        public Nullable<double> YTVALUE { get; set; }
        public Nullable<double> CURRENTVALUE { get; set; }
        public string YCID { get; set; }
        public string YXID { get; set; }
        public string ENCODESCHEME { get; set; }
        public Nullable<int> CHANNEL { get; set; }
        public Nullable<double> MULTIPLEVALUE { get; set; }
    }
}
