//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblykparam
    {
        public string CONTROLAREA { get; set; }
        public int ID { get; set; }
        public string NAME { get; set; }
        public string STATIONID { get; set; }
        public string YKKIND { get; set; }
        public string CMDELEMENTID { get; set; }
        public Nullable<int> CMDELEMENTSTYLE { get; set; }
        public string UPPER_CZH { get; set; }
        public string UPPER_YKYTH { get; set; }
        public Nullable<int> UPPER_YKYTVALUE { get; set; }
        public string LOWER_CZH { get; set; }
        public string LOWER_YKYTH { get; set; }
        public Nullable<int> LOWER_YKYTVALUE { get; set; }
        public Nullable<int> CHANNEL { get; set; }
        public string YCID { get; set; }
        public string YXID { get; set; }
    }
}
