//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblyxvalue
    {
        public string CONTROLAREA { get; set; }
        public string EQUIPMENTID { get; set; }
        public string ID { get; set; }
        public string NAME { get; set; }
        public string SUBSTATIONID { get; set; }
        public string SHORTCUT { get; set; }
        public string CZH { get; set; }
        public string YXH { get; set; }
        public string ZFCZH { get; set; }
        public string ZFYXH { get; set; }
        public Nullable<int> VALUESTYLE { get; set; }
        public Nullable<int> CHANNEL { get; set; }
        public Nullable<int> YXVALUE { get; set; }
        public Nullable<System.DateTime> REFRESHTIME { get; set; }
        public Nullable<int> OFFSETVALUE { get; set; }
        public Nullable<int> MULTIPLEVALUE { get; set; }
        public Nullable<bool> NOTFRESH { get; set; }
        public Nullable<bool> REPLACED { get; set; }
        public Nullable<int> REPLACEDVALUE { get; set; }
        public Nullable<bool> ESTIMATORREPLACED { get; set; }
        public Nullable<int> ESTIMATEDVALUE { get; set; }
        public string CHOOSESTATE { get; set; }
        public Nullable<int> GRAPHID { get; set; }
    }
}
