//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcurvedetail
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string SUBSTATIONID { get; set; }
        public string SUBSTATIONNAME { get; set; }
        public int CURVETYPE { get; set; }
        public string TARGETTABLE { get; set; }
        public string TARGETFIELD { get; set; }
        public string TARGETELEMENTID { get; set; }
        public string TARGETELEMENTNAME { get; set; }
        public string TARGETUNIT { get; set; }
        public Nullable<int> VALIDATION { get; set; }
        public Nullable<double> AXISYMAXVALUE { get; set; }
        public Nullable<double> AXISYMINVALUE { get; set; }
        public Nullable<int> VALIDUPPERBOUND { get; set; }
        public Nullable<int> VALIDLOWERBOUND { get; set; }
    }
}
