//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcommandrecord
    {
        public int ID { get; set; }
        public Nullable<int> SCHEMEID { get; set; }
        public string SCHEMENAME { get; set; }
        public Nullable<System.DateTime> CMDDATETIME { get; set; }
        public string CMDELEMENTID { get; set; }
        public Nullable<int> CMDELEMENTSTYLE { get; set; }
        public string CMDELEMENTNAME { get; set; }
        public string CMDCONTENT { get; set; }
        public string CMDKIND { get; set; }
        public string CMDACTION { get; set; }
        public string CMDRESULT { get; set; }
        public string SOUNDLIST { get; set; }
        public Nullable<int> SENDTAG { get; set; }
        public Nullable<int> SHOWTAG { get; set; }
        public string SBTIME { get; set; }
        public Nullable<int> GRAPHID { get; set; }
    }
}
