//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedlinesegment
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string ALIASNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string FEEDLINEID { get; set; }
        public string CONDUCTORTYPEID { get; set; }
        public Nullable<double> LENGTH { get; set; }
        public Nullable<double> R { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> G { get; set; }
        public Nullable<double> B { get; set; }
        public string VOLTAGELEVELID { get; set; }
        public Nullable<double> EXPECTLIFETIME { get; set; }
        public Nullable<bool> ISCENTRAL { get; set; }
        public Nullable<System.DateTime> STARTUSINGTIME { get; set; }
        public Nullable<int> FEEDID { get; set; }
    }
}
