//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedssts
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string ALIASNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VOLTAGELEVELID { get; set; }
        public Nullable<int> SOURCEBUSA { get; set; }
        public Nullable<int> SOURCEBUSB { get; set; }
        public Nullable<double> DY1 { get; set; }
        public Nullable<double> DY2 { get; set; }
        public Nullable<double> FH1I { get; set; }
        public Nullable<double> FH2I { get; set; }
        public Nullable<double> DLGL { get; set; }
        public Nullable<double> XWJDZ { get; set; }
        public Nullable<double> SJDZ { get; set; }
        public Nullable<double> GZMSDZ { get; set; }
        public Nullable<double> DY1HFDYXXDZ { get; set; }
        public Nullable<double> DY1HFDYSXDZ { get; set; }
        public Nullable<double> DY2HFDYXXDZ { get; set; }
        public Nullable<double> DY2HFDYSXDZ { get; set; }
        public Nullable<double> FHDLBH { get; set; }
        public Nullable<double> PTGZBH { get; set; }
        public Nullable<double> CTGZBH { get; set; }
        public Nullable<double> JCQJHBH { get; set; }
        public Nullable<double> JCQWZYCBH { get; set; }
        public Nullable<double> EXPECTLIFETIME { get; set; }
        public Nullable<System.DateTime> STARTUSINGTIME { get; set; }
        public Nullable<int> GRAPHID { get; set; }
    }
}
