//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedcapacitorcontrol
    {
        public string ID { get; set; }
        public int PUTONYXVAL { get; set; }
        public int PUTOFFYXVAL { get; set; }
        public int DISTANTYXVAL { get; set; }
        public int LOCALYXVAL { get; set; }
        public int PUTONYKVAL { get; set; }
        public int PUTOFFYKVAL { get; set; }
        public int DISTANTYKVAL { get; set; }
        public int LOCALYKVAL { get; set; }
        public int VOLCTRLMODYCVAL { get; set; }
        public int COSCTRLMODYCVAL { get; set; }
        public int VOLCTRLMODYTVAL { get; set; }
        public int COSCTRLMODYTVAL { get; set; }
        public Nullable<int> QCTRLMODYCVAL { get; set; }
        public Nullable<int> QCTRLMODYTVAL { get; set; }
    }
}
