//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgraphtopoterminal
    {
        public int RowID { get; set; }
        public string NAME { get; set; }
        public string CAPTION { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> TAG { get; set; }
        public string VOL { get; set; }
        public Nullable<int> STID { get; set; }
        public Nullable<int> LINKCOUNT { get; set; }
        public string LINKS { get; set; }
        public Nullable<int> EQUIPCOUNT { get; set; }
        public Nullable<int> GRAPHID { get; set; }
        public Nullable<int> FEEDID { get; set; }
        public string LINK { get; set; }
        public string LINKFOOT { get; set; }
        public Nullable<int> PARENTID { get; set; }
    }
}
