//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllva
    {
        public string ID { get; set; }
        public Nullable<int> SCHEMEID { get; set; }
        public Nullable<int> VOLTAGELEVELID { get; set; }
        public Nullable<int> FEEDBUSID { get; set; }
        public Nullable<int> DISTRIBTRANSID { get; set; }
    }
}
