//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvcDb.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltransformertype
    {
        public string ID { get; set; }
        public string TYPENAME { get; set; }
        public Nullable<int> WINETYPE { get; set; }
        public Nullable<bool> ISAUTOTRANSFORMER { get; set; }
        public Nullable<bool> ISOLTC { get; set; }
        public Nullable<double> NOLOADLOSS { get; set; }
        public Nullable<double> EXCITINGCURRENT { get; set; }
        public Nullable<double> HWRC { get; set; }
        public Nullable<double> HWRV { get; set; }
        public Nullable<double> HWSCL { get; set; }
        public Nullable<double> HWSCV { get; set; }
        public Nullable<double> HWR { get; set; }
        public Nullable<double> HWX { get; set; }
        public Nullable<double> MWRC { get; set; }
        public Nullable<double> MWRV { get; set; }
        public Nullable<double> MWSCL { get; set; }
        public Nullable<double> MWSCV { get; set; }
        public Nullable<double> MWR { get; set; }
        public Nullable<double> MWX { get; set; }
        public Nullable<double> LWRC { get; set; }
        public Nullable<double> LWRV { get; set; }
        public Nullable<double> LWSCL { get; set; }
        public Nullable<double> LWSCV { get; set; }
        public Nullable<double> LWR { get; set; }
        public Nullable<double> LWX { get; set; }
        public Nullable<double> G { get; set; }
        public Nullable<double> B { get; set; }
        public Nullable<double> UNITPRICE { get; set; }
        public Nullable<bool> LOCALCHOICE { get; set; }
    }
}
